# -*- coding: utf-8 -*-
"""chat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lPxa6S2kRw0YZnrYPp3cuBVndeQV4W76
"""

import google.generativeai as genai
import pickle
import os
from datetime import datetime

class CompleteHealthBot:
    def __init__(self, gemini_api_key=None):
        self.current_step = "welcome"
        self.conversation_history = []
        self.user_interests = []
        self.gemini_api_key = gemini_api_key
        self.use_gemini = gemini_api_key is not None

        # Initialize Gemini if API key provided
        if self.use_gemini:
            try:
                genai.configure(api_key="AIzaSyC9YtWbSCbiPFI2BVX_y6rG-A7ZdIBa0UA")
                self.model = genai.GenerativeModel('gemini-pro')
                print("✅ Gemini AI initialized successfully!")
            except Exception as e:
                print(f"❌ Gemini initialization failed: {e}")
                self.use_gemini = False

        # Built-in knowledge base for fallback
        self.knowledge_base = {
            "greetings": [
                "🤗 Hello! Welcome to HealthData Marketplace! I'm here to help you with secure health data sharing.",
                "😊 Hi there! So glad you're here! I help people earn income while contributing to medical research.",
                "👋 Welcome! I'm your friendly health data assistant. Ready to explore how you can make a difference?"
            ],
            "earnings": {
                "basic": "$50-1500 for general health info",
                "fitness": "$80-2000/month for activity data",
                "sleep": "$60-1500/month for sleep patterns",
                "medical": "$100-3000 for health records",
                "genetic": "$200-5000 for DNA data",
                "images": "$150-3000 for medical scans"
            },
            "security": [
                "🔒 AI anonymization removes all personal identifiers",
                "⛓️ Blockchain ensures your consent is permanent",
                "🔐 Military-grade encryption protects your data",
                "👁️ Researchers only see patterns, never personal info"
            ],
            "process": [
                "1. Choose what data to share (2 mins)",
                "2. Set privacy preferences (3 mins)",
                "3. AI anonymizes your data",
                "4. Researchers access safe data",
                "5. You get paid automatically!"
            ]
        }

    def get_gemini_response(self, user_message):
        """Get AI-enhanced response from Gemini"""
        if not self.use_gemini:
            return None

        try:
            context = f"""
            You are a friendly, helpful health data marketplace assistant. The user is asking about sharing health data to earn income.

            Conversation context:
            - Current step: {self.current_step}
            - User interests: {self.user_interests}
            - Previous messages: {self.conversation_history[-3:] if self.conversation_history else 'None'}

            User's current message: "{user_message}"

            Respond in a warm, friendly, conversational tone. Be helpful and informative about health data sharing, earnings, security, and the process. Keep responses concise and engaging. Use emojis occasionally.

            If the user seems confused or asks unrelated questions, gently guide them back to health data topics.
            """

            response = self.model.generate_content(context)
            return response.text
        except Exception as e:
            print(f"Gemini API error: {e}")
            return None

    def chat(self, message):
        """Main chat method with Gemini fallback"""
        # Add to conversation history
        self.conversation_history.append({
            'role': 'user',
            'message': message,
            'timestamp': datetime.now()
        })

        # Try Gemini first if available
        if self.use_gemini:
            gemini_response = self.get_gemini_response(message)
            if gemini_response:
                self.conversation_history.append({
                    'role': 'assistant',
                    'message': gemini_response,
                    'timestamp': datetime.now(),
                    'source': 'gemini'
                })
                return gemini_response

        # Fallback to built-in responses
        response = self._builtin_response(message)
        self.conversation_history.append({
            'role': 'assistant',
            'message': response,
            'timestamp': datetime.now(),
            'source': 'builtin'
        })

        return response

    def _builtin_response(self, message):
        """Built-in response system"""
        message_lower = message.lower().strip()

        # Track user interests
        if any(word in message_lower for word in ["earn", "money", "income"]):
            self.user_interests.append("earnings")
        if any(word in message_lower for word in ["safe", "secure", "privacy"]):
            self.user_interests.append("security")
        if any(word in message_lower for word in ["how", "work", "process"]):
            self.user_interests.append("process")
        if any(word in message_lower for word in ["data", "share", "what i have"]):
            self.user_interests.append("data_types")

        # Handle different conversation steps
        if self.current_step == "welcome":
            return self._handle_welcome(message_lower)
        elif self.current_step == "main_discussion":
            return self._handle_main_discussion(message_lower)
        elif self.current_step == "detailed_info":
            return self._handle_detailed_info(message_lower)
        else:
            return self._handle_fallback(message_lower)

    def _handle_welcome(self, message):
        """Handle welcome conversation"""
        if any(word in message for word in ["hi", "hello", "hey", "start", "hey"]):
            self.current_step = "main_discussion"
            return """🤗 Hello there! Welcome to HealthData Marketplace!

I'm so glad you stopped by! I help people like you safely share health data with medical researchers and earn income while making a difference.

What would you like to know about today? You can ask me about:

💰 **Earning potential** - How much you can make
🔒 **Data security** - How we protect your privacy
🔄 **The process** - How everything works
📊 **Data types** - What kind of health data you can share
🚀 **Getting started** - How to begin

What's on your mind? 😊"""

        return "👋 Hi! I'm here to help with health data sharing. Type 'hello' to get started!"

    def _handle_main_discussion(self, message):
        """Handle main discussion topics"""
        # Earnings questions
        if any(word in message for word in ["earn", "money", "income", "make money", "how much", "price"]):
            earnings_info = "\n".join([f"• {desc}" for desc in self.knowledge_base["earnings"].values()])
            return f"""💰 **Earning Potential:**

{earnings_info}

**Additional factors:**
• Rare conditions can earn more
• Continuous data earns monthly income
• Genetic data has high one-time value

Want more specific pricing for your situation?"""

        # Security questions
        elif any(word in message for word in ["safe", "secure", "privacy", "protect", "anonymous"]):
            security_info = "\n".join([f"• {point}" for point in self.knowledge_base["security"]])
            return f"""🔒 **Your Privacy is Protected:**

{security_info}

**You maintain full control:**
✅ Choose what data to share
✅ Set usage preferences
✅ Withdraw consent anytime
✅ See who accesses your data

Feel better about the security? What else would you like to know?"""

        # Process questions
        elif any(word in message for word in ["how", "work", "process", "step"]):
            process_info = "\n".join(self.knowledge_base["process"])
            return f"""🔄 **How It Works:**

{process_info}

**Total setup time:** ~10 minutes
**Time to first payment:** 7-10 days
**Payment frequency:** Weekly

Ready to learn how to get started?"""

        # Data type questions
        elif any(word in message for word in ["data", "share", "what i have", "type", "kind"]):
            return """📊 **Data Types We Accept:**

**Digital Health Data:**
• Fitness tracker data (steps, heart rate, sleep)
• Smartphone health app data
• Wearable device information

**Medical Data:**
• Health records & history
• Lab test results
• Medical images (X-Ray, MRI, CT scans)
• Genetic/DNA data

**Personal Health Data:**
• Symptoms you track
• Medication information
• Lifestyle habits

What type of health data do you have? I can give you specific info!"""

        # Getting started
        elif any(word in message for word in ["start", "begin", "setup", "get started", "sign up"]):
            self.current_step = "detailed_info"
            return """🚀 **Ready to Get Started? That's Awesome!**

Here's your simple path to begin earning:

**Step 1: Explore** (2 minutes)
Visit our website to see how it works

**Step 2: Setup** (8 minutes)
Create account and connect your data

**Step 3: Earn** (Ongoing)
Receive automatic payments

**What you'll need:**
• Email address
• Health data sources (phone, apps, records)
• 10 minutes of time

Would you like the website link to get started now?"""

        # General questions
        elif "?" in message:
            return "🤔 That's a great question! Could you tell me a bit more about what you're looking for? I can help with earnings, security, the process, or getting started."

        # Default response for unclear messages
        else:
            return """😊 Thanks for your message! I want to make sure I help you with exactly what you need.

Could you tell me what you're most interested in?
• How much you could earn
• How your data is protected
• How the process works
• What data you can share
• How to get started

I'm here to help with whatever you need!"""

    def _handle_detailed_info(self, message):
        """Handle detailed information requests"""
        if any(word in message for word in ["yes", "ready", "start", "begin", "website", "link"]):
            return """🎉 **Excellent! Let's Get You Started!**

**Website:** HealthDataMarketplace.com

**When you visit:**
1. Take the virtual tour (optional)
2. Create your free account
3. Connect your data sources
4. Set your preferences
5. Start earning!

**Pro Tips:**
• Start with just one data type if you're unsure
• You can always add more data later
• Support is available 24/7 if you need help

**Welcome Bonus:** Use code **FRIEND100** for extra earnings! 🎁

You're about to start earning while helping medical research - how amazing is that? 🌟

Any questions before you get started?"""

        elif any(word in message for word in ["no", "not yet", "later", "wait"]):
            self.current_step = "main_discussion"
            return "😊 No problem at all! Take your time. I'll be here when you're ready. Is there anything else you'd like to know about in the meantime?"

        else:
            return "🚀 Ready to begin your journey? Just say 'yes' and I'll give you all the details to get started!"

    def _handle_fallback(self, message):
        """Handle any unexpected messages"""
        return """🤗 I want to make sure I'm helping you with what you need!

Could you tell me what brought you here today? I can help with:

• Understanding how much you can earn
• Learning how your data is protected
• Explaining how the process works
• Showing you how to get started
• Answering any other questions

What would be most helpful for you right now? 😊"""

    def save_chatbot(self, filename="health_bot.pkl"):
        """Save chatbot state to file"""
        try:
            with open(filename, 'wb') as file:
                pickle.dump(self, file)
            return f"✅ Chatbot saved to {filename}"
        except Exception as e:
            return f"❌ Error saving: {e}"

    @staticmethod
    def load_chatbot(filename="health_bot.pkl"):
        """Load chatbot from file"""
        try:
            with open(filename, 'rb') as file:
                bot = pickle.load(file)
            return bot, "✅ Chatbot loaded successfully!"
        except FileNotFoundError:
            return None, "❌ No saved chatbot found"
        except Exception as e:
            return None, f"❌ Error loading: {e}"

def main():
    """Main function to run the chatbot"""

    # Try to load existing bot
    bot, message = CompleteHealthBot.load_chatbot()

    if bot is None:
        print("Creating new chatbot...")
        # You can add your Gemini API key here
        GEMINI_API_KEY = "YOUR_GEMINI_API_KEY_HERE"  # Replace with your actual API key

        if GEMINI_API_KEY == "YOUR_GEMINI_API_KEY_HERE":
            print("ℹ️  No Gemini API key provided. Using built-in responses.")
            bot = CompleteHealthBot()
        else:
            bot = CompleteHealthBot(gemini_api_key=GEMINI_API_KEY)

    print("=" * 60)
    print("🤗 COMPLETE HEALTH DATA CHATBOT")
    print("=" * 60)
    print("💡 I can help with: Earnings • Security • Process • Getting Started")
    print("🔧 Type 'save' to save progress, 'quit' to exit")
    print("\n" + bot.chat("hello"))

    while True:
        try:
            user_input = input("\n💬 You: ").strip()

            if user_input.lower() in ['quit', 'exit', 'bye']:
                # Save before quitting
                save_msg = bot.save_chatbot()
                print(f"🤗 {save_msg}")
                print("Thanks for chatting! Visit HealthDataMarketplace.com to get started! 👋")
                break

            elif user_input.lower() == 'save':
                save_msg = bot.save_chatbot()
                print(f"💾 {save_msg}")
                continue

            elif user_input.lower() == 'status':
                print(f"📊 Current step: {bot.current_step}")
                print(f"💬 Chat history: {len(bot.conversation_history)} messages")
                print(f"🤖 Using Gemini: {bot.use_gemini}")
                continue

            if user_input:
                response = bot.chat(user_input)
                print(f"🤗 {response}")
            else:
                print("🤗 I'm listening...")

        except KeyboardInterrupt:
            print("\n\n🤗 Session saved! Come back anytime!")
            bot.save_chatbot()
            break
        except Exception as e:
            print(f"🤗 Oops! Something went wrong: {e}")

if __name__ == "__main__":
    main()